version: '3.8'

services:
    web:
        build: .
        container_name: v3-server
        ports:
            - "8002:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_DATABASE=timesheet_dev
            - DB_USERNAME=user
            - DB_PASSWORD=password

    db:
        image: mysql:5.7
        container_name: db-server
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: timesheet_dev
            MYSQL_USER: user
            MYSQL_PASSWORD: '@password'
        volumes:
            - db_data:/var/lib/mysql
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        ports:
            - "3307:3306"

volumes:
    db_data:
