name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run Npm Install
      run: npm install
    - name: Install Redux
      run: npm install react-redux
    - name: Install Redux Toolkit
      run: npm install @reduxjs/toolkit
    - name: Run NPM Build
      run: npm run build
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
      
  deploy:
    name: Deploy to Production Server
    needs: laravel-tests  # Ensure tests pass before deploying
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch pushes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Production Server
        env:
          USER: farai
          SERVER: ${{ secrets.SERVER_IP }}
          APP_DIR: /var/www/timesheet-app
        run: |
          ssh $USER@$SERVER "
          cd $APP_DIR && sudo git fetch &&  sudo git merge origin main && sudo npm run build &&
           # Run migrations
          sudo php artisan migrate --force
          # Add any additional commands here, like installing dependencies or restarting services
          "      
